# Generated by Django 5.2.3 on 2025-06-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('assigned_market', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FabricCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_update_date', models.DateField()),
                ('fabric_type', models.CharField(max_length=50)),
                ('fabric_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50, unique=True)),
                ('number_of_traders_registered', models.IntegerField(default=0)),
                ('collection_day', models.CharField(max_length=50)),
                ('assigned_agent', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_catalogue.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('market_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('date_enrolled', models.DateField()),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_catalogue.market')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('estimated_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pickup_schedules', 'Pickup Schedules'), ('pickup_completed', 'Pickup Completed')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_catalogue.fabriccatalogue')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_catalogue.trader')),
            ],
        ),
    ]
